// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Summary.Data;

#nullable disable

namespace Summary.Migrations
{
    [DbContext(typeof(MytimeContext))]
    partial class MytimeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Summary.Data.MyTime", b =>
                {
                    b.Property<int>("currentIndex")
                        .HasColumnType("int")
                        .HasColumnName("currentIndex")
                        .HasColumnOrder(0);

                    b.Property<DateTime>("createDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("createDate")
                        .HasColumnOrder(1);

                    b.Property<TimeSpan>("endTime")
                        .HasMaxLength(10)
                        .HasColumnType("time");

                    b.Property<TimeSpan>("lastTime")
                        .HasMaxLength(10)
                        .HasColumnType("time");

                    b.Property<string>("note")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<TimeSpan>("startTime")
                        .HasMaxLength(10)
                        .HasColumnType("time");

                    b.Property<string>("type")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("userid")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("currentIndex", "createDate");

                    b.ToTable("MyTime");
                });
#pragma warning restore 612, 618
        }
    }
}
